require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - test_prof/rubocop

AllCops:
  Exclude:
    - 'node_modules/**'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Guardfile'
    - 'db/**'
    - 'db/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

RSpec/Capybara/FeatureMethods:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/ArgumentAlignment:
  Exclude:
    - 'app/views/**/*'

Layout/HashAlignment:
  Exclude:
    - 'app/views/**/*'

Layout/TrailingWhitespace:
  Exclude:
    - 'app/views/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**'
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/**'
    - 'config/**/*'

RSpec/AggregateExamples:
  Enabled: true
  Include:
    - 'spec/**/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**'
    - 'spec/views/**'
    - 'spec/views/**/*'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/views/**/*.rb'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/**/*.rb'

RSpec/FilePath:
  CustomTransform:
    API: api
    APIs: apis

RSpec/ImplicitSubject:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/views/**/*.rb'
    - 'spec/features/**/*.rb'

Style/Documentation:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/Lambda:
  Enabled: true
  Exclude:
    - 'app/models/**/*.rb'

Style/SwapValues:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true
